version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=marketless
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresmarketless
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=marketless
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresmarketless
      - POSTGRES_HOST=db
